name: Build

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Xcode versions
        run: ls -ld /Applications/Xcode*.app
      - name: Setup Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Archive framework for iPhone simulator
        run: |
          xcodebuild archive \
            -scheme BeyondWordsPlayer \
            -configuration Release \
            -sdk iphonesimulator \
            -archivePath './build/BeyondWordsPlayer.framework-iphonesimulator.xcarchive' \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            SKIP_INSTALL=NO
      - name: Build Player framework
        run: |
          xcodebuild clean build \
            -workspace BeyondWordsPlayer.xcworkspace \
            -scheme BeyondWordsPlayer \
            -configuration Debug \
            -sdk iphonesimulator \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            ARCHS=arm64
