name: Release

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push BeyondWordsPlayer.podspec
      - name: List Xcode versions
        run: ls -ld /Applications/Xcode*.app
      - name: Setup Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Archive framework for iPhone simulator
        run: |
          xcodebuild archive \
            -scheme BeyondWordsPlayer \
            -configuration Release \
            -sdk iphonesimulator \
            -archivePath './build/BeyondWordsPlayer.framework-iphonesimulator.xcarchive' \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            SKIP_INSTALL=NO
      - name: Archive framework for iPhone
        run: |
          xcodebuild archive \
            -scheme BeyondWordsPlayer \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "./build/BeyondWordsPlayer.framework-iphoneos.xcarchive" \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            SKIP_INSTALL=NO
      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
            -framework "./build/BeyondWordsPlayer.framework-iphoneos.xcarchive/Products/Library/Frameworks/BeyondWordsPlayer.framework" \
            -framework "./build/BeyondWordsPlayer.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/BeyondWordsPlayer.framework" \
            -output "./build/BeyondWordsPlayer.xcframework"
      - name: Archive the XCFramework
        run: cd build && zip -r BeyondWordsPlayer.xcframework.zip ./BeyondWordsPlayer.xcframework
      - name: Upload build artifact to GitHub release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./build/BeyondWordsPlayer.xcframework.zip
          asset_name: BeyondWordsPlayer.xcframework.zip
          overwrite: true
